spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bootbank_loan_db?currentSchema=bootbank_loan_db
    username: ${DB_USERNAME:bootbank_loan}
    password: ${DB_PASSWORD:dev12345}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bootbank_loan_db


  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: bootbank_loan_db