spring:
  application:
    name: bootbank-loan-ms #changed to bootbank-loan-ms
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  profiles:
    include:
      - db
server:
  servlet:
    context-path: /bootbank-loan-ms #changed to bootbank-loan-ms



